import type { Metadata } from "next";
import { Inter, Hind_Vadodara } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import { Web3Modal } from "@/providers/web3ModalProvider";

const inter = Inter({ subsets: ["latin"] });

const hindVadodara = Hind_Vadodara({
  weight: ["700", "300", "400", "600", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={hindVadodara.className}>
        <Web3Modal>{children}</Web3Modal>
      </body>
    </html>
  );
}
